### ISSUE TITLE
Leaderboard kullanılınca başka user gösteriyor

### ISSUE THREAD

**Issue by Teo00** [fluxteam/IssueTracker#1]
**Başlamadan önce;**
- [] Daha önceden önerilen özellikleri kontrol ettim. (Köşeli parantezin içine 'X' yazınız)
- [] Botun gerekli izinlerinin olup olmadığını kontrol ettim. (Köşeli parantezin içine 'X' yazınız)

**Bu hata raporunu şu bot için açtım;**
Buraya yaşadığınız hatanın hangi bot ile yaşandığını yazınız. (WordBot, FluxBot...)

**Hatanın açıklaması;**
Hatanın öz, temiz ve detaylı açıklaması.

**Yeniden üretme adımları;**
Bu davranışı yeniden üretmek için gereken adımlar:
1. Şu kanala gidin '...'
2. Şu komutu kullanın '....'
3. Şunu ayarlayın '....'
4. Hatayı gözlemleyin

**Beklenen davranış;**
Olması beklenen davranışın öz, temiz ve detaylı açıklaması.

**Yerine görülen davranış;**
Yerine görülen davranışın öz, temiz ve detaylı açıklaması.

**Ekran görüntüleri;**
Mümkünse, problemi detaylandırmak adına ekran görüntüleri ekleyin.

**Sunucu ID'si;**
Yaşanan problemin yaşandığı sunucunun ID'sini buraya girin.

**Ek bilgiler;**
Problem hakkındaki herhangi bir ek bilgiyi buraya ekleyin.

**Comment by Zamion101** [comment]
Başlamadan önce kısmındaki yerler kontrol edilmemiş durumda.
Hata'nın yaşandığı Bot belirlenmemiş.
Hatanın açıklaması çok kısa.
Hatanın oluşturulma adımları yetersiz.
Beklenen davranış yetersiz bilgi içeriyor.
Yerine görülen davranış yetersiz bilgi içeriyor.
Sunucu ID'si girilmemiş.

Rapor içeriğindeki eksikler ve yetersiz bilgiler sebebi ile Rapor kapatılmıştır.

**Comment by Zamion101** [comment]
@Zamion101 @Hagfog @Teo00 #1 
Duplicate of #1

- [X ]  1

- [ ]  2

```py
import discord
embed = discord.Embed()
await ctx.send(embed=embed)
```
