### ISSUE TITLE
WordCoin Şikayeti.

### ISSUE THREAD

**Issue by GameMonsterT** [fluxteam/IssueTracker#11]
**Başlamadan önce;**
- [x] Daha önceden önerilen özellikleri kontrol ettim. Benzer bir öneri yok. (Köşeli parantezin içine 'X' yazınız)
- [x] (HATA ALIYORSANIZ DOLDURUN) Botun gerekli izinlerinin olup olmadığını kontrol ettim. (Köşeli parantezin içine 'X' yazınız)

**Bu fikir/öneri şu bot için;**
WordBot

**Önerdiğiniz özellik bir hataya bağlı mı? Lütfen açıklayın;**
Tek kelime kullanabilme hakkından dolaylı şikayet.

**Kendi ürettiğiniz çözüm;**
Sadece bir öneri.

**Bu çözüme ürettiğiniz alternatifler;**
Yok.

**Sunucu ID'si;**
788392350043996190

**Ek bilgiler;**
Merhabalar FluxTeam ekibi. İssue'ma hoş geldiniz. Bugün sizlere çok güzel bir issue hazırladım. Umarım beğenirsiniz. Hadi issue'ya geçelim.
Öncelikle Şu mevzuya değinmek istiyorum. WordCoin. Şu anda, her kullanıcının bir mesaj atma hakkı var. Şimdilik test aşamasında. Ve %35 olmasına rağmen şikayet var. Ama oran %5 olduğu zaman, çok fazla şikayet olacaktır. Bu yüzden her kullanıcıya, "iki" mesaj hakkı vermenizi tavsiye ederim. Bu neyi değiştirir? Birinci mesaj, her zaman olduğu gibi kullanılır. Lakin üye o kadar kelime yazdıktan sonra, attığı mesajlardan birinde özel kelime çıktığında, WordCoin kazanamamak kullanıcının öfkelenmesine neden olur. İkinci kelime hakkı burada işe yarar olacaktır. Kullanıcı, Oyunun içinde, birinci mesajı atar ve özel kelime gelirse her kullanıcı gibi onunda WordCoin kazanma hakkına sahip olması gerekir. Bu yüzden her kullanıcıya iki mesaj hakkı verilmelidir. Peki, ikinci mesajı attığında özel kelime gelirse ne olacak? Her kelime yazıldığında, özel kelime çıkması %5 olasılık ile kesindir. Lakin ikinci mesaj hakkı kullanıcının insiyatifine kalmıştır. Şöyle ki; birinci kelimede %5 ihtimal vardır. Ancak ikinci kelime %5 risk üzerine kuruludur. Üye, olur da ikinci kelime hakkını kullanırsa, bu onun sorumluluğuna aittir. Bir kaç puan kazanmak için riske girmek onun tercihidir.
(Bu konu hakkında sormak istediğiniz bir yer olursa Discord'tan bana ulaşabilirsiniz.)
Umarım issue'yu beğenmişsinizdir. Böyle issue'lar gelmesini istiyorsanız. İssue'ma destek olmayı, beğenmeyi ve kategorileştirmeyi unutmayın. Yeni issue'lar da görüşmek üzere. By. (Aklımda fena fikirler var yalnız.)

**Comment by Teo00** [comment]
Kişinin üst üste iki kere yazmasıyla risk faktörü eleneceğinden, bu özellik yakın zamanda hayata geçirilmeyecektir.
Ayrıca lütfen raporları kısa ve öz yazmaya dikkat edelim. 
Teşekkür ederim.

**Comment by Zamion101** [comment]
Kelime oyunu yapısı gereği `sıra tabanlı` oyunlar kategorisine girmektedir. Sıra tabanlı bir oyunda sıranızı saldıktan sonra karşıdaki kişi hamlesini yapmadan siz hamlenizi yapamazsınız. En basit örnek `Satranç`. Eğer satrançta her rakibin 2 hamle yapma hakkı olsaydı o zaman büyük bir kaos yaşanır ve oyunun zevki kaybolurdu. Hiçbir sıra tabanlı oyunda bir kişinin 2 kere hamle yapma hakkı yoktur. Vermiş olduğunuz öneri/fikir bu oyun türünün yapı taşlarından birini yok etmeye eş değerdir. Bunun dışında özel kelime olasılı `5%` olmak ile birlikte herkesin yazdığı kelimeden özel kelime çıkma riski aynıdır. Bunu kendiniz için düşündüğünüzde de bir başkası için düşündüğünüzde de aynıdır. Kısa bir örnek olarak 3 kişi oyun oynuyor ve bu 3 kişi yazdığı her kelimede 5% şansla özel kelime çıkmasına sebep oluyor. Bu durumda özel kelime çıkmasına sebep olan kelimeyi yazan kişi 5% şans ile bu duruma sebep olmuştur aynı durum diğerleri içinde geçerlidir. Bu denklemde hiçbir taraf üzerinde haksızlık durumu yoktur. Bu denklem tamamen kişinin şans faktörüne dayanmaktadır. Bu yüzden şuan için öneriniz'i hayata geçirme gibi bir düşünce bulunmamaktadır.
