### ISSUE TITLE
KoiosBot "korona" komutu çalışmıyor.

### ISSUE THREAD

**Issue by GameMonsterT** [fluxteam/IssueTracker#12]
**Başlamadan önce;**
- [x] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok. (Köşeli parantezin içine 'X' yazınız)
- [x] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor. (Köşeli parantezin içine 'X' yazınız)

**Bu hata raporunu şu bot için açtım;**
Buraya yaşadığınız hatanın hangi bot ile yaşandığını yazınız. (WordBot, FluxBot...)

**Hatanın açıklaması;**
Kullanıcı komutu k!korona, kullanılmaya çalışıldığında herhangi tepki alınmıyor.

**Yeniden üretme adımları;**
Bu davranışı yeniden üretmek için gereken adımlar:
1. KoiosBot'un bulunduğu herhangi bir sunucuya gidin
2. Şu komutu kullanın 'k!korona'
3. Hatayı gözlemleyin

**Beklenen davranış;**
 Türkiye için korona virüs istatistiklerini göstermesi.

**Yerine görülen davranış;**
Herhangi bir eylemde bulunmuyor. Hatalı çalışma yok. Hiç çalışmıyor.

**Ekran görüntüleri;**
Yok.

**Sunucu ID'si;**
602852388432510987

**Ek bilgiler;**
Yok.

**Comment by Hagfog** [comment]
Komut hali hazırda kaldırılmıştı. Yardım komutundan da kaldırıldı.
