### ISSUE TITLE
KoiosBot, web sitesi hata veriyor.

### ISSUE THREAD

**Issue by GameMonsterT** [fluxteam/IssueTracker#13]
**Başlamadan önce;**
- [x] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok. (Köşeli parantezin içine 'X' yazınız)
- [x] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor. (Köşeli parantezin içine 'X' yazınız)

**Bu hata raporunu şu bot için açtım;**
KoiosBot

**Hatanın açıklaması;**
koiosbot.me web sitesin de giriş yaptıktan sonra, sunucu seçiminde hata veriyor.

**Yeniden üretme adımları;**
Bu davranışı yeniden üretmek için gereken adımlar:
1. KoiosBot'un bulunduğu herhangi bir kanal
2. Şu komutu kullanın 'k!otorol'
3. Size verilen web sitesine gidin ve giriş yapın. Ardından yetki verilecek sunucuyu seçin.
4. Hatayı gözlemleyin.

**Beklenen davranış;**
KoiosBot'un, seçilen sunucuya sorunsuzca bağlanması.

**Yerine görülen davranış;**
"Application error" (uygulama hatası)

**Ekran görüntüleri;**
![Ekran Görüntüsü (46)](https://user-images.githubusercontent.com/78109294/106410851-dea02600-6454-11eb-9b85-0d75392d8d98.png)

**Sunucu ID'si;**
802570891891572766

**Ek bilgiler;**
Yok

**Comment by Hagfog** [comment]
Sorunun farkındaydım. Düzeltmek için bir güncelleme yapıldı şu anlık sorun çözülmüş gibi görünüyor. Sorunun tam olarak çözülüp çözülmediği onaylanana kadar issue açık kalacaktır.

**Comment by Teo00** [comment]
Sorunun güncel olarak çözüldüğü onaylanmıştır. Yeniden aynı sorunla karşılaşırsanız yeni bir issue açıp bu issue'yu etiketleyebilirsiniz.
