### ISSUE TITLE
WordLang Ya da WordBot LL (language learning) 

### ISSUE THREAD

**Issue by GameMonsterT** [fluxteam/IssueTracker#15]
**Başlamadan önce;**
- [x] Daha önceden önerilen özellikleri kontrol ettim. Benzer bir öneri yok. (Köşeli parantezin içine 'X' yazınız)
- [] (HATA ALIYORSANIZ DOLDURUN) Botun gerekli izinlerinin olup olmadığını kontrol ettim. (Köşeli parantezin içine 'X' yazınız)

**Bu fikir/öneri şu bot için;**
WordBot

**Önerdiğiniz özellik bir hataya bağlı mı? Lütfen açıklayın;**
Hata kaynaklı bir öneri değildir.

**Kendi ürettiğiniz çözüm;**
Yok

**Bu çözüme ürettiğiniz alternatifler;**
Yok

**Sunucu ID'si;**
Yok

**Ek bilgiler;**
Bildiğimiz gibi WordBot, sadece kendi dilimiz için kullanılıyor. İngiliz biri için İngilizce, Türk biri için Türkçe olarak.
Peki ya WordBot'u dil öğrenmek için kullanamaz mıyız? Misal Türk biri WordLang oynamak istiyor.
Öğrenmek istediği dil İngilizce olsun. Oyunun içindeki komutlar İngilizce ama açıklamalar Türkçe olacak.
Oyun başlatma komutu şu olacak mesela; WordBot'un prefix'i, kendi dili ve ardından öğrenmek istediği dil. 
(wb.başlat tr_TR en_US) ya da (wb.başlat tr_US) gibi vs.
Şöyle olacak... oyun başladı ve "Türk" oyuncular "İngilizce" kelimeler yazmaya başladı.
Örnek:
wb.başlat tr_US (kelimeler akmaya başlar.)
"start, teacher, real, langauge, episode, ethernet, vb."
Oyunculardan biri anlamını bilmediği kelimeyi yazar. 
wb.dictionary episode 
Bu durumda WordBot kelimenin Türkçe anlamını ve Türk sürümünde kullanıldığı gibi Türkçe manasını'da verir.
"ingilizce >> episode"  "Türkçe >> bölüm"
1. Meaning "Bir bütünü oluşturan parçaların her biri, kısım"
2. Meaning "Bir kuruluşun yönetim birimlerinden her biri, departman, seksiyon"
3. Meaning "Çağ, devir"
4. Meaning "Canlıların bölümlenmesinde filumların bir araya gelmesiyle oluşan birlik"
5. Meaning "Bir okul veya üniversitenin herhangi bir bilim ve uzmanlık dalında eğitim sağlayan birimlerinden her biri, departman"
6. Meaning "Bölme işlemi sonunda elde edilen sayı"

Yani sadece eğlence botu değil çok az'da olsa, dil geliştirme / öğrenme botu olarak'ta işlev görür.
Reklam yaparken de "Arkadaşlarınız ile Hem eğlenip Hem dilinizi geliştirmek istemez misiniz? O zaman WordBot'u sunucunuza davet edin https://wordbot.xyz/tr_invite vsvs."
(Bunu geliştirmek size kalmış. İngiliz biri Türkçe öğrenmek istediği zaman "wb.start en_TR" sayesinde türkçesini geliştirebilir.)
(Ayrıca WordBot beta'da olduğu gibi WordCoin ya da diğer önerimde olduğu gibi iki kelime hakkının kullanımına engel olan bir durumda bulunmuyor. Rahatça Çalışabilir.)
(Çok fazla veri kullanır gibi şeyler söyleyecekseniz. Hiç yorum yapmanıza gerek yok. Kodlamazsınız olur biter.)

**Comment by Zamion101** [comment]
Veri kullanımı bu durum için hiçbir sorun değildir. Sıkıntı şu TDK her ne kadar kendisi ```bedava``` olarak anlamları verse de aynı özgürlüğü diğer sözlük siteleri vermemektedir. Hatta şuan kullanmakta olduğumuz İngilizce sözlük hiçbir şekilde anlamları ```desteklemekte/içermemektedir```. Bu özgürlüğü sağlayan sözlük siteleri ile daha önce görüşülmüş sponsorluk/kısıtlı izin/api izni tarzı gerekli olan isteklerde bulunulmuş fakat geri dönütlerin hiçbir zaman olumlu olmamasından dolayı WordBot'un diğer dilleri destekleme süreci gerilemiştir. Eğer bildiğiniz ```bedava``` yada ```geliştirici dostu``` sözlük siteleri biliyorsanız. Bu konu üzerinde durulacaktır.

**Comment by Teo00** [comment]
Böyle bir platform bulunana kadar bu issue kapatılmıştır.
