### ISSUE TITLE
KoiosBot Ana dili Türkçe olan sunucuda ingilizce çalışıyor.

### ISSUE THREAD

**Issue by GameMonsterT** [fluxteam/IssueTracker#16]
**Başlamadan önce;**
- [x] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok. (Köşeli parantezin içine 'X' yazınız)
- [x] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor. (Köşeli parantezin içine 'X' yazınız)

**Bu hata raporunu şu bot için açtım;**
KoiosBot

**Hatanın açıklaması;**
KoiosBot Ana dili Türkçe olan sunucuda komutlar Türkçe olmasına rağmen İngilizce çalışıyor.

**Yeniden üretme adımları;**
Bu davranışı yeniden üretmek için gereken adımlar:
1. KoiosBot'un bulunduğu herhangi bir kanala gidin.
2. Şu komutu kullanın. 'k!davet'
3. Sunucunuza davet ettikten sonra dil ayarlarını kontrol edin. Ve komutları çalıştırın.
4. Hatayı gözlemleyin.

**Beklenen davranış;**
KoiosBot'un bulunduğu sunucunun ana dilinde çalışması gereklidir.

**Yerine görülen davranış;**
İngilizce çalışıyor.

**Ekran görüntüleri;**
![Ekran Görüntüsü (47)](https://user-images.githubusercontent.com/78109294/106495694-1480f100-64cd-11eb-8892-ae922cc3b8df.png)
![Ekran Görüntüsü (48)](https://user-images.githubusercontent.com/78109294/106495728-1cd92c00-64cd-11eb-9414-1bcae01b245d.png)

**Sunucu ID'si;**
802570891891572766

**Ek bilgiler;**
KoiosBot'u sunucudan çıkarıp tekrar aldım. Yine olmadı.
Hatta farklı bir hesap açtım. Ve yeni bir sunucu kurdum. Yine olmadı.

**Comment by Zamion101** [comment]
Bu bir hata değildir. Her bir sunucu `Topluluk Sunucusu` değildir bu nedenden dolayı bot tercih edilen sunucu dilini kendi veritabanında saklar. Bu durum tüm botlar için aynıdır. `k!dil` veya `k!language` komutları ile botun tercih edilen sunucu dili değiştirilir. Bunun dışında hiçbir şekilde stabil bir tercih ve her bir sunucunun `Topluluk Sunucusu` olmadığı için atılan ekran görüntüsündeki değer kaile alınmaz.
