### ISSUE TITLE
KoiosBot Dashboard'a Giriş Sorunu

### ISSUE THREAD

**Issue by acengiiz** [fluxteam/IssueTracker#20]
**Başlamadan önce;**
- [x] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok. (Köşeli parantezin içine 'X' yazınız)
- [x] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor. (Köşeli parantezin içine 'X' yazınız)

**Bu hata raporunu şu bot için açtım;**
KoiosBot

**Hatanın açıklaması;**
KoiosBot websitesinde dashboarda girmeye çalıştığımda giremeyip ekran görüntüleri kısmına eklediğim hatayı aldım.

**Yeniden üretme adımları;**
Bu davranışı yeniden üretmek için gereken adımlar:
1. KoiosBot websitesine gidin. (https://koiosbot.me)
2. Sağ üstten Discord hesabınızla giriş yapın.
3. Bir süre beklemeniz ardından hatayı gözlemleyin. 

**Beklenen davranış;**
KoiosBot'un websitesinde bulunan dashboarda erişim.

**Yerine görülen davranış;**
KoiosBot'un websitesinde bulunan dashboarda erişim hatası.

**Ekran görüntüleri;**
![image](https://user-images.githubusercontent.com/78107978/106528842-1f9a4800-64f2-11eb-9bb6-e7fad4fc0dcd.png)
![image](https://user-images.githubusercontent.com/78107978/106528873-2fb22780-64f2-11eb-8eb2-b8ccada5d89c.png)
![image](https://user-images.githubusercontent.com/78107978/106529122-9fc0ad80-64f2-11eb-94ee-2c4de337ea47.png)

**Ek bilgiler;**
Hatayı yeniden üretim kodlarını kullanarak en az 5 kez denedim. Her denememde aynı hatayı aldığımdan dolayı hata raporu oluşturdum.

**Comment by acengiiz** [comment]
Ayrıca aynı hatayı en son ekran görüntüsündeki sayfayı kapatıp (https://koiosbot.me) sayfasındaki nickimin üzerine bastığımda da aldım.

**Comment by Hagfog** [comment]
KoiosBot websitesinin Dashboard bölümü geçici süreliğine devre dışı bırakılmıştır.
