### ISSUE TITLE
WordBot Beta, yıldız tepkisini vermiyor.

### ISSUE THREAD

**Issue by GameMonsterT** [fluxteam/IssueTracker#24]
## Kontroller
- [x] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok.  
- [x] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor. 

## Problemin yaşandığı Bot(lar);

- [ ] WordBot
- [x] WordBot Beta
- [ ] KoiosBot
- [ ] Postcard
- [ ] FluxBot

## Yeniden üretme adımları

1. FluxTeam kanalına gidin.
2. Oyunu bir süre oynayın.
3. Özel kelime çıktığı zaman.
4. Hatayı gözlemleyin

## Beklenen davranış
Özel kelime çıktığında, ondan önceki kelimenin yıldız tepkisi alması.

## Yerine görülen davranış
Tik tepkisi alıyor.

## Ekran görüntüleri
![Ekran Görüntüsü (49)](https://user-images.githubusercontent.com/78109294/106630286-bfa4af80-658c-11eb-8eaf-30e103070059.png)

**Comment by Teo00** [comment]
Sorunun devam ettiği gözlenmiştir.

**Comment by Zamion101** [comment]
Bu bir sorun değildir. Her bir özel kelime 10 saniyelik süre zarfında yazılmalıdır. Bu süre zarfı geçtiği zaman kabul edilmemektedir. Kabul edilen kelimelere ise yıldız tepkisi verilir.

**Comment by Teo00** [comment]
Hata olmadığı tespit edildiği için issue'yu kapatıyorum.
