### ISSUE TITLE
Special Word süresi bitince mesajın silinmesi

### ISSUE THREAD

**Issue by HasanAbi38** [fluxteam/IssueTracker#25]
**Başlamadan önce;**
- [x] Daha önceden önerilen özellikleri kontrol ettim. Benzer bir öneri yok. (Köşeli parantezin içine 'X' yazınız)
- [] (HATA ALIYORSANIZ DOLDURUN) Botun gerekli izinlerinin olup olmadığını kontrol ettim. (Köşeli parantezin içine 'X' yazınız)

**Bu fikir/öneri şu bot için;**
WordBot

**Önerdiğiniz özellik bir hataya bağlı mı? Lütfen açıklayın;**
Special Word'ün belirtildiği mesajın sürekli oyunda kalması. Kullanıcılar ekran görüntüsünde olduğu gibi kelimenin süresinin bittiğini farketmeyip WordCoin almaya çalışabilirler. Ayrıca bence kelime kullanılamadığı halde sohbette o mesajın bulunması gereksiz kalabalık oluyor gibi.

**Kendi ürettiğiniz çözüm;**
Special Word'ün belirtildiği mesajın 10 saniyelik süresi dolunca oyundan silinmesi. 

**Bu çözüme ürettiğiniz alternatifler;**
Ürettiğiniz alternatif çözümlerin ve/veya ek özelliklerin öz, temiz ve detaylı açıklaması. Örneğin: "Ayrıca [...] da yapılabilir."

**Sunucu ID'si;**
788392350043996190

**Ek bilgiler;**
![wb](https://user-images.githubusercontent.com/52089200/106645575-9b050380-659d-11eb-98e9-ecfd54708f2d.png)

**Comment by Zamion101** [comment]
Öncelikle geç cevap için özür dilerim. Yapmış olduğunuz öneri dikkate alınmış ve Beta sürümünde aktif hale getirilmiştir.
