### ISSUE TITLE
(Fikir/Öneri) WordBot Beta, Kişiye özel tepki önerisi.

### ISSUE THREAD

**Issue by GameMonsterT** [fluxteam/IssueTracker#26]
**Başlamadan önce;**
- [x] Daha önceden önerilen özellikleri kontrol ettim. Benzer bir öneri yok. (Köşeli parantezin içine 'X' yazınız)
- [] (HATA ALIYORSANIZ DOLDURUN) Botun gerekli izinlerinin olup olmadığını kontrol ettim. (Köşeli parantezin içine 'X' yazınız)

**Bu fikir/öneri şu bot için;**
WordBot Beta

**Önerdiğiniz özellik bir hataya bağlı mı? Lütfen açıklayın;**
Hata kaynaklı değildir.

**Kendi ürettiğiniz çözüm;**
Yok.

**Bu çözüme ürettiğiniz alternatifler;**
Yok.

**Sunucu ID'si;**
788392350043996190

**Ek bilgiler;**
WordBot'un çoklu oyun içinde kişiselleştirilmesi her ne kadar küçük bir detay bile olsa kullanıcılar için hoş bir özellik olacaktır.
WordBot içinde onaylı kelime yazıldığı vakitler'de oyuncular belirleyebiliyor ise, kendi seçtikleri tepki, her onaylı kelime yazdıklarında, WordBot, o tepkiyi onlar için ekleyecektir. Eğer belirleme şansları yoksa, WordBot, her onaylı kelime için rastgele bir tepki verebilir. (Tepki ikinci bir tepki olarak değil, tik tepkisinin yerine eklenecektir.)

**Comment by k0jo666** [comment]
Buna ek olarak wordcoin market açıldığında wordcoin markette satın alınabilecek tepkiler olabilir, bu şekilde birisi wordcoin harcayarak kendi mesajlarına özel bir tepki alabilir, bence hem oynanma zevkini hem de oyuncuya ek bir amaç katacağı için oynanma sıklığını arttırır.

**Comment by acengiiz** [comment]
Bende kendi fikirlerimi sunayım.WorBot'un özel kelimelere eklediği tepkiler önceden oluşturulmuş bir havuzdan random bir şekilde eklenebilir.Ayrıca tepkiler olarak şunuda eklemek isterim.Worbot'a eklenecek bir komut ile oynanan oyunda bıraktığı ifadeler insanların kendi dc sunusuna eklediği emojilerle değiştirilebilir.

**Comment by Zamion101** [comment]
> Worbot'a eklenecek bir komut ile oynanan oyunda bıraktığı ifadeler insanların kendi dc sunucusunda bulunan emojilerle değiştirilebilir.Böylelikle insanlar WordBot'u kendi sunucusunda özelleştirmiş olurlar.

Bu fikir Beta'da aktif olarak kullanılmaktadır. `wb.ayarlar-oyun aem ❤` yada `wb.ayarlar-oyun onay_emoji ❤` komutu ile WordBot'un onaylanan mesajlara eklediği tepki değiştirilebilmektedir.

> Buna ek olarak wordcoin market açıldığında wordcoin markette satın alınabilecek tepkiler olabilir, bu şekilde birisi wordcoin harcayarak kendi mesajlarına özel bir tepki alabilir, bence hem oynanma zevkini hem de oyuncuya ek bir amaç katacağı için oynanma sıklığını arttırır.

Açıkcası bu fikir fazlasıyla hoşuma gitti. Dediğiniz gibi oyunun oynanma zevkini arttıracak bir fikir. En kısa zaman içinde ilk prototipleri Beta'ya getirmeyi düşünmekteyim.


 Gelişmelerin takibi için issues'u açık bırakıyorum.
