### ISSUE TITLE
KoiosBot k!wasted Komutu

### ISSUE THREAD

**Issue by qreardedwashere** [fluxteam/IssueTracker#3]
[x] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok.
[x] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor.

**_Bu hata raporu KoiosBot için açıldı._**

**Hatanın açıklaması;**
Eğlence komutu k!wasted, komutu kullanmaya çalışıldığında herhangi tepki alınmıyor.

**Yeniden üretme adımları;**
Bu davranışı yeniden üretmek için gereken adımlar:
1. KoiosBot'un olduğu sunucuya girin.
2. Herhangi bir kanalda **k!wasted** komutunu girin.
4. Hatayı gözlemleyin.

**Beklenen davranış;**
Yardım menüsünde de belirtildiği gibi, etiketlenen kişinin avatarına **wasted** efektini uygulaması.

**Yerine görülen davranış;**
Komut kullanıldığında herhangi bir cevap veya geri dönüş alınmıyor.

**Ekran görüntüleri;**
[Screenshot_20210130-182234~2.png](https://user-images.githubusercontent.com/65084643/106360331-f1b5d780-6328-11eb-9b24-7195723edf14.png)

**Sunucu ID'si;**
669250312078360576

**Ek bilgiler;**
KoiosBot'un mesajı başka bir bot tarafından silindiği kontrol edildi. Ancak herhangi bir şeye rastlanmadı.

Ekran görüntüsünde **/** ile kullanıldığını görüyorsunuz. Bot prefixi **/** olarak değiştirildi.

**Comment by Hagfog** [comment]
Durumdan haberdarım. Komut KoiosBot'un yeni sürüm güncellemesinden sonra bir takım sıkıntılardan dolayı devre dışı kalmıştır. İlerleyen günlerde yapılacak güncelleme ile düzeltilecektir.

**Comment by Hagfog** [comment]
Komut yeniden aktifleştirilmiştir.
