### ISSUE TITLE
Profil Kodu

### ISSUE THREAD

**Issue by Dead0Queen** [fluxteam/IssueTracker#30]
## Kontroller
- [X] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok. 
- [X] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor.

## Problemin yaşandığı Bot(lar);

- [X] WordBot Beta

## Hatanın açıklaması
wb.profil yazınca hata veriyor.

## Yeniden üretme adımları

1. Şu kanala gidin 'wb-lab'
2. Şu komutu kullanın 'wb.profil'
3. Şunu ayarlayın '  '
4. Hatayı gözlemleyin

## Beklenen davranış
Wordbot profilimizin gösterilmesi

## Yerine görülen davranış
 Else | cannot identify image file <_io.BytesIO object at 0x0000020CB404D270> | <class 'PIL.UnidentifiedImageError'> 
bu hatayı veriyor 

## Sunucu Bilgileri
Yaşanan problemin yaşandığı Sunucu'ya ait temel bilgiler. 
###### Kanal ID:798315933038542888

**Comment by Zamion101** [comment]
Sorun WordBot Redis'e kullanıcı resmini kaydederken yaşanan sorundan dolayı oluşmuştur. Bu tür bir hatanın gelecekte tekrar yaşanmaması adına önlemler alınmıştır. Sorun şuan için çözüme kavuşmuş durumdadır.
