### ISSUE TITLE
(Fikir/Öneri) WordBot, Bonus WordCoin önerisi.

### ISSUE THREAD

**Issue by GameMonsterT** [fluxteam/IssueTracker#31]
## Kontroller
- [x] Daha önceden açılan fikirleri/önerileri kontrol ettim ve aşağıda belirteceğim fikre/öneriye benzer bir fikir/öneri bulamadım. 
- [ ] Bu fikri/öneriyi bir hata'nın çözümü adına yapmaktayım. 

## Fikrin/Önerinin ait olduğu Bot(lar);

- [x] WordBot
- [ ] KoiosBot
- [ ] Postcard
- [ ] FluxBot

## Fikrinizi/Önerinizi detaylı bir şekilde açıklayınız.
WordBot 24 saat içerisinde, rastgele bir vakitte, 1 dakikalığına yazılan her kelime için WordCoin verecek.
Bu vakitten kimsenin haberi olmayacak. Sadece denk gelebilen kişiler alacak.
Böyle bir özellik olduğundan haberleri de olmayacak. İlk başta sunucu bazlı olmasını isteme nedenim, daha az insanın ulaşmasını istememdendi. Global bazlı olunca denk düşme ihtimali artıyordu. Ama tabi ki zor olduğu için sunucu bazlı olmadı.
"Sunucu bazlı değil Global bazlı olacak."

## Fikrinize/Önerinize ait altenatif(ler)
Bu fikrime/önerime ait bir alternatif yoktur.

## Ekstra eklemek istedikleriniz
Bu fikrime/önerime ait bir ek yoktur.

**Comment by Teo00** [comment]
Bot'un kısıtlı limitleri ve bazı durumlar nedeniyle büyük ihtimalle yakın zamanda böyle bir özellik eklenmeyecektir. Fakat yine de bu özelliği tekrar değerlendireceğiz. Issue'yu açık bırakıyorum.

**Comment by Zamion101** [comment]
Ek bilgi olarak lütfen açtığınız issues'ları düzenleme yapmayanız değişiklikleri mesaj olarak yazmanızı rica edeceğim böylecene ileriki bir zamanda issue'a tekrar bakılınca issues'un zaman içinde nasıl geliştiğini görmek daha kolay olacaktır.
