### ISSUE TITLE
(Fikir/Öneri) WordBot wb.sıralama Önerisi

### ISSUE THREAD

**Issue by qreardedwastaken** [fluxteam/IssueTracker#32]
- [x] Daha önceden açılan fikirleri/önerileri kontrol ettim ve aşağıda belirteceğim fikre/öneriye benzer bir fikir/öneri bulamadım. 

- [x] **WordBot**

**Belirtilen fikir/öneri:**
wb.sıralama Komutu 10 kişinin sıralamasını göstermekle kalmamalı. **wb.sıralama 2-3-4-5** Gibi bir şey eklenebilir, daha fazla kişinin sıralaması görüntülenebilir. 

**Bir alternatif belirtilmedi.**

 **Bir ek belirtilmedi.**

**Comment by Zamion101** [comment]
Aslında bu fikir gayet ilgi çekici. Fakat sorun şurada şuanki tasarım söz konusu olunca sıralama olarak herhangi bir sıra numarası yazmamakta bu durumda kişinin kaçıncı sırada olduğunu anlamak zor olacaktır. Bu fikir sıralama tasarımında muhtemel bir değişikliğe yol açacaktır. Bu konuda @ysfchn 'ın fikri önemli oluyor. Yusuf'tan gelecek cevaba göre fikir konusunda daha fazla konuşmak mümkündür.
