### ISSUE TITLE
(Fikir/Öneri) Harf puanlarının gösterilmesi

### ISSUE THREAD

**Issue by HasanAbi38-zz** [fluxteam/IssueTracker#34]
## Kontroller
- [x] Daha önceden açılan fikirleri/önerileri kontrol ettim ve aşağıda belirteceğim fikre/öneriye benzer bir fikir/öneri bulamadım. 
- [ ] Bu fikri/öneriyi bir hata'nın çözümü adına yapmaktayım. 

## Fikrin/Önerinin ait olduğu Bot(lar);

- [x] WordBot
- [ ] KoiosBot
- [ ] Postcard
- [ ] FluxBot

## Fikrinizi/Önerinizi detaylı bir şekilde açıklayınız.

Hangi harfin kaç puana sahip olduğu wb.puan vb. bir komutla gösterilmesi. 
Bu sayede kelime yazılmadan önce kaç puan alınacağı hesaplanabilir yada kullanıcıların puanlamanın nasıl yapıldığına dair kafalarında soru işareti oluşması önlenebilir.

## Fikrinize/Önerinize ait altenatif(ler)

Bu fikrime/önerime ait bir alternatif yoktur.

**Comment by Zamion101** [comment]
Bahsettiğiniz `wb.puan` komutu `wb.skor` komutu ile aynı görevi taşımaktadır. Fakat ekstra olarak belirttiğiniz `vb. bir komut` açısından bakacak olursak şuan için aklıma gelen `wb.puan-listesi` yada `wb.puan-hesapla`. Eğer başka bir öneriniz varsa komut için lütfen belirtin.

**Comment by HasanAbi38** [comment]
wb.puanlama
wb.harf-puan
 
şimdilik aklımda olanlar bunlar. ekstra komut bulabilirsem bildiririm.
