### ISSUE TITLE
(Fikir/Öneri) Booster özellikleri

### ISSUE THREAD

**Issue by MertBhey** [fluxteam/IssueTracker#36]
## Kontroller
- [x] Daha önceden açılan fikirleri/önerileri kontrol ettim ve aşağıda belirteceğim fikre/öneriye benzer bir fikir/öneri bulamadım. 
- [ ] Bu fikri/öneriyi bir hata'nın çözümü adına yapmaktayım. 

## Fikrin/Önerinin ait olduğu Bot(lar);

- [x] WordBot
- [ ] KoiosBot
- [ ] Postcard
- [ ] FluxBot

## Fikrinizi/Önerinizi detaylı bir şekilde açıklayınız.

FluxTeam sunucusunu ve/veya WordBot destek sunucusunu boostlayan üyeler için profillerine **Booster** rozeti eklenebilir, bunun yanında özel kelime yazdıklarında 10% veya daha az bir olasılıkla 1 yerine 2 veya daha fazla WordCoin verilmesi eklenebilir.

## Fikrinize/Önerinize ait altenatif(ler)

Bu fikre ait herhangi bir alternatif yoktur.

## Ekstra eklemek istedikleriniz

Bu fikre ait herhangi bir ek yoktur.

**Comment by Zamion101** [comment]
`Booster` rozeti fikri kulağa ilgi çekici geliyor. Ayrıca belirttiğiniz `10% veya daha az bir olasılıkla 1 yerine 2 veya daha fazla WordCoin verilmesi` önerisi hakkında bir sorum var. `5%'lik` Özel Kelime olasılığının içinde mi bu durum. Yani 5% şans ile Özel Kelime çıktı ve çıkan kelime içinde de 10% ihtimal ile `Booster` olanlar 1 yerine 2 adet WordCoin kazanacak doğru mudur?

**Comment by MertBhey** [comment]
Evet

**Comment by MertBhey** [comment]
Buna ek olarak eğer 2 (veya daha fazla) wordcoin kazandıysa mesajın sonuna  "FluxTeam sunucusunu boostladığı için ekstra coin kazandı!" tarzı bir mesaj eklenebilir

**Comment by ysfchn** [comment]
Bence profiline Booster rozeti eklenebilir fakat onun dışında kendisine WordCoin'ler ile ek avantaj vermek ne kadar mantıklı bilmiyorum. Booster'lar için sunucuda "Booster" rolüne sahip olması ve profilinde "Booster" rozeti olması yeterince bir avantaj bence. Yoksa diğer türlü "pay-to-win" tarzında bir yola gitmiş oluruz.

Bu duruma bir örnek olarak, Discord botları, hiçbir şekilde kullanıcının Nitro'su var mı yok mu diye kontrol edemiyor. (API izin vermiyor). Ve yanlış hatırlamıyorsam, Discord, kullanıcının parayla ödediği Discord öğelerine göre botların çeşitli ödüller vermesini pek hoş karşılamıyor diye biliyorum.

O yüzden, oy vermek gibi para gerektirmeyen ve herkesin ulaşabileceği bir şekilde ödül vermek daha mantıklı gibime geliyor.
