### ISSUE TITLE
WordBot Kelime Türetme Hatası

### ISSUE THREAD

**Issue by qreardedwastakennN** [fluxteam/IssueTracker#37]
## Kontroller
* [x] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok.
* [X] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor. Botun kanala özel yetkisi bulunmakta.

## Problemin yaşandığı Bot(lar);
* [X] WordBot
* [ ] WordBot Beta
* [ ] KoiosBot
* [ ] Postcard
* [ ] FluxBot

## Hatanın açıklaması
Kelime türetme sırasında **ad** kelimesi girildi. Ancak bot bunu **e** harfi ile başlıyor olarak varsaydı.

## Yeniden üretme adımları
1. WordBot'u Türkçe dilinde bir kanalda başlatın.
2. Oyunu oynarken **ad** kelimesini giriş yapın.
4. Hatayı gözlemleyin

## Beklenen davranış
**ad** Kelimesi girildiğinde botun bu kelimeyi **d** harfiyle bittiğini görmesi ve oyunun devamında **d** harfiyle devam etmemiz.

## Yerine görülen davranış
**ad** Kelimesi d harfiyle bitti, ancak oyuna **eski** kelimesiyle devam edildi.

## Ekran görüntüleri
[Buradan fotoğrafa ulaşın.](http://qreardedwashere.cf/ingredients/photos/wordbot_bug_report_by_qreardedwastaken.png)

**Comment by qreardedwastakennN** [comment]
Fotoğraftaki kişinin mesajının silindiğini [buradan](http://qreardedwashere.cf/ingredients/photos/wordbot_bug_report_by_qreardedwastaken_p2.png) görüntüleyebilirsiniz.

**Comment by Zamion101** [comment]
`ad` yazılan mesaj saat `11.35`'de gönderilmiş ve onay almıştır. Bundan sonraki gönderilen `.ne alaka` mesajı ise saat `12.00`'da atılmış. Bu süre içerisinde araya bir kişi mesaj yazmış ve o mesajı yazan kişi kendi mesajını silmiş olabilir. Bu durumda yeni yazılması gereken kelimenin baş harfi `d` yerine `e` olarak değişmiş olabilir. Örnek: 
ad (son harf d)
~anne (Mesaj silinir) (son harf e)~
deniz (WordBot hata verir çünkü son harf e olması gerekiyor)

**Comment by qreardedwastakennN** [comment]
11:40'da **dede** kelimesi yazılmış ardından silinmiş fotoğraftaki kişi 11:56'da **dal** yazılmış ve silinmiş. Herhangi bir mesaj silme durumu söz konusu gibi gözükmüyor. Botlar tarafından bildirilen loglar kontrol edildi. Aralarında görmemiş olabilme ihtimalim yüksek ancak mesaj silinme durumu pek söz konusu gibi durmuyor.

**Comment by Zamion101** [comment]
`11:40'da dede kelimesi yazılmış ardından silinmiş.` (**silinmiş**) bunu diyen sizsiniz ardından neden `Herhangi bir mesaj silme durumu söz konusu gibi gözükmüyor.` yazıyorsunuz? Benim yazdığınızdan anladığım `11.35: ad` ardından `11.40: dede (Mesaj siliniyor, son harf e olarak değişiyor)` ve en son ise `12.00: deniz` kelimesi yazılıyor, ki bu durumda silinen mesaj `e` ile bittiği için başlanması gereken harf `e` oluyor `d` değil.

**Comment by Teo00** [comment]
Sorunun var **olmadığı** onaylanmış, aşağıda ekran görüntüsü paylaşılmıştır.

Olası yaşıyor olabileceğiniz problemler;
> `ad` yazılan mesaj saat `11.35`'de gönderilmiş ve onay almıştır. Bundan sonraki gönderilen `.ne alaka` mesajı ise saat `12.00`'da atılmış. Bu süre içerisinde araya bir kişi mesaj yazmış ve o mesajı yazan kişi kendi mesajını silmiş olabilir. Bu durumda yeni yazılması gereken kelimenin baş harfi `d` yerine `e` olarak değişmiş olabilir. Örnek:
> ad (son harf d)
> ~dede (Mesaj silinir) (son harf e)~
> deniz (WordBot hata verir çünkü son harf e olması gerekiyor)

Ek olarak;
Zaman zaman lag ve ping faktöründen kaynaklı, gerek discord gerek client tabanlı sorunlar yaşanabilmektedir. Böyle sorunlar için elimizden gelen bir çözüm şuanlık bulunmamaktadır. Fakat daha iyi bir oyun deneyimi için daimi olarak çalışmaktayız. 

Değerli hata raporlarınız için teşekkür ediyoruz. Issue'yu geçersiz olduğu onaylandığı için kapatıyorum.

![image](https://user-images.githubusercontent.com/20708105/108578950-c75aa700-7335-11eb-858e-378ca70a3639.png)

EDIT:

Daha detaylı verilen bir cevap;

> `11:40'da dede kelimesi yazılmış ardından silinmiş.` (**silinmiş**) bunu diyen sizsiniz ardından neden `Herhangi bir mesaj silme durumu söz konusu gibi gözükmüyor.` yazıyorsunuz? Benim yazdığınızdan anladığım `11.35: ad` ardından `11.40: dede (Mesaj siliniyor, son harf e olarak değişiyor)` ve en son ise `12.00: deniz` kelimesi yazılıyor, ki bu durumda silinen mesaj `e` ile bittiği için başlanması gereken harf `e` oluyor `d` değil.
