### ISSUE TITLE
Özel kelime mesajındaki emojinin yazı olarak kalması

### ISSUE THREAD

**Issue by rravenus** [fluxteam/IssueTracker#38]
## Kontroller
- [X] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok.  
- [X] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor. 

## Problemin yaşandığı Bot(lar);

- [ ] WordBot
- [X] WordBot Beta
- [ ] KoiosBot
- [ ] Postcard
- [ ] FluxBot

## Hatanın açıklaması
Özel kelime ortaya çıktığında ve/veya yazıldığında bot tarafından atılan mesajdaki :wb_language: emojisinin yazı olarak kalması

## Yeniden üretme adımları

1. Aktif oyun kanalına gidin
2. Özel kelime gelene kadar oynayın
3. Botun attığı mesajı gözlemleyin

## Beklenen davranış
İlk ekteki gibi emojinin aktifleşmesi.

## Yerine görülen davranış
2 ve 3. ekte gözüktüğü gibi emojinin :wb_language: şeklinde kalması.

## Ekran görüntüleri
![3](https://user-images.githubusercontent.com/78051799/108897073-c328d500-7626-11eb-8c9f-0acca99e30c1.png)
![2](https://user-images.githubusercontent.com/78051799/108897142-d50a7800-7626-11eb-9a28-209331a8787f.png)
![1](https://user-images.githubusercontent.com/78051799/108897147-d63ba500-7626-11eb-91f8-67a54d2026a6.png)

**Comment by Zamion101** [comment]
Sorunun Kanal üzerindeki yetkilerden kaynaklandığını düşünüyorum. @ysfchn kontrolleri sağlayacaktır.

**Comment by ysfchn** [comment]
Botun sunucuda "Harici Sunuculardan Emoji Kullan" yetkisi halihazırda bulunuyor, fakat sadece `@everyone` rolü için kapalıydı. Fakat görünüşe göre WordBot, mesajı webhook ile gönderdiği için `@everyone` için ayarlanan tüm izinler, webhook'un kendisini de etkiliyor. 

Sunucudaki izinleri düzenleyerek `@everyone` için "Harici Sunuculardan Emoji Kullan" yetkisine izin verdim. İzin verdikten sonra emojilerin tekrar gözüktüğü gözlemleniyor. 

İzinlerle alakalı bir sorun olduğu ve WordBot'un bu olay ile alakalı maalesef yapabileceği bir şeyi olmadığından dolayı bu issue'u kapatıyorum.
