### ISSUE TITLE
WordBot feedbacklerinde yanlış dil hatası

### ISSUE THREAD

**Issue by Teo00** [fluxteam/IssueTracker#4]
**Başlamadan önce;**
- [x] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok. (Köşeli parantezin içine 'X' yazınız)
- [x] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor. (Köşeli parantezin içine 'X' yazınız)

**Bu hata raporunu şu bot için açtım;**
WordBot Beta (2.2.0-development [201612])

**Hatanın açıklaması;**
Oyun Türkçe başlatılmasına rağmen bot İngilizceymiş gibi feedback veriyor. Fakat Türkçe sözlük üzerinden kontrol ediyor.

**Yeniden üretme adımları;**
Bu davranışı yeniden üretmek için gereken adımlar:
1. Oyun oynayacağınız kanala gidin.
2. wb.oyna --oyun kelime_oyunu --dil tr_TR --limit 100 ile oyunu başlatın.
3. Oyunu birkaç kişi ile oynayın.
4. Botun Türkçe sözlükte olmayan bir kelimeye verdiği cevabın, özel kelimeleri belirtirken attığı mesajın ve bunun gibi bildirdiği geri bildirimlerin dilini gözlemleyin.

**Beklenen davranış;**
Botun Türkçe bir şekilde cevap vermesi.

**Yerine görülen davranış;**
Bot İngilizce açılmış gibi feedback veriyor. Fakat oyun Türkçe kelimelerle dönüyor.

**Ekran görüntüleri;**
![image](https://user-images.githubusercontent.com/20708105/106360564-25453180-632a-11eb-985e-4442d16bb325.png)
![image](https://user-images.githubusercontent.com/20708105/106360608-6d645400-632a-11eb-9975-03cab9184bf2.png)

**Sunucu ID'si;**
FT Lab

**Ek bilgiler;**
Ekran görüntülerinde görüldüğü gibi, bot İngilizce sözlüğe baktığını söylese bile Türkçe sözlüğü kontrol ediyor.

**Comment by Zamion101** [comment]
Bu durumun farkındayım. Bu durum dil dosyasının daha Türkçe karşılığının olmaması sonucu İngilizce karşılığını kullanmasından kaynaklanmaktadır. WordBot'un kod üzerindeki bir hatası değildir. İlerleyen günlerde Türkçe dil dosyası sisteme tanımlanınca bu durum ortadan kalkacaktır.
