### ISSUE TITLE
(Fikir/Öneri) WordBot Küfür Engelleyici

### ISSUE THREAD

**Issue by qreardedwastaken** [fluxteam/IssueTracker#40]
## Kontroller
- [x] Daha önceden açılan fikirleri/önerileri kontrol ettim ve aşağıda belirteceğim fikre/öneriye benzer bir fikir/öneri bulamadım.

- [x] WordBot

## Fikir/Öneri Açıklaması
**wb.yasakla** Komutunu kullanarak bir küfür kelimesini yasaklamak gibi uzun uğraştırıcı işler yerine bunu kısa bir komutla çözümlendirebiliriz. Küfür engelleyici/filtresi. Örnek olarak **wb.küfür-engelleyici aç** gibi bir komut.

## Ekstra eklemek istenilen
Bazı sunucular küfür konusunda hassas davranabilir ve bunu önlemek onlar için biraz uğraştırıcı olabilir. Açıkçası bunu ben denemeye çalışsaydım direkt vazgeçerdim.

**Comment by mehmetcdc** [comment]
Hangi seviye argoları küfür olarak ayarlayacaksın? Senin küfür olarak kabul edebileceğin bir argoyu başkası kabul etmeyebilir, mesela filtreyi açtın; filtre içerisinde bir kelime küfür olarak geçiyor ama küfür sayılabilecek derecede değildir. Bunu küfür olarak saymasını başkaları istemeyebilir. Bu yüzden biraz daha farklı bir yapı oluşturmak daha güzel ve özelleştirilebilir olur kendimce

**Comment by MertBhey** [comment]
Türkçedeki tüm argoları/küfürleri toplamak ve güncel toplamak inanılmaz derecede zor olacaktır, ayrıca yukarda da dendiği gibi bu tür şeyler göreceli olabilir. Küfür eden kullanılacalar için ekstra bir rol oluşturulup o rol yasaklı üye rolü olarak kullanılabilir.
