### ISSUE TITLE
(HATA/BUG) WordBot Dil Değiştirirken Görünen Hata 

### ISSUE THREAD

**Issue by qreardedwastakennN** [fluxteam/IssueTracker#42]
- [x] Daha önceden açılmış hata raporlarını kontrol ettim. 
- [x] Botun gerekli izinlerinin olup olmadığını kontrol ettim. 
- [] Bu hata raporunu doldururken hiçbir kısmı silmedim.

- [x] WordBot

## Hatanın açıklaması
WordBot'u her sunucuya eklediğimde dil değiştirme sırasında hep bir hata ile karşılaşıyorum. Komutun kullandığı kanalda WordBot'un normal istenilen yetkiden fazla yetkisi bulunmasına rağmen bir hata ile karşılaşıyorum.

## Yeniden üretme adımları
- wordbot.xyz Adresine girin ve WordBot'u sunucunuza ekleyin.
- WordBot'u ekledikten sonra aktif olup olmadığının kontrolünü sağlayın.
- WordBot dilini **wb.language tr_TR** komutuyla değiştirmeye çalışın.
- Durumu gözlemleyin.

## Beklenen davranış
Konut kullanıldığında dil değiştirildiğine dair hatasız bir mesaj göndermesi.

## Yerine görülen davranış
Komut kullanımı yapıldığında bir hata yazısı vermesi.

## Ekran görüntüleri
![Screenshot_20210320-201918~3.png](https://user-images.githubusercontent.com/78941156/111880167-d5462b00-89ba-11eb-908c-e07e2af6734a.png)

## Sunucu Bilgileri
Sunucu ID: **807004408868372501**
Kanal ID: **822757643932139541**

Bu issue arka arkaya 2-3 gözlemden sonra alınan karara göre açıldı.

**Comment by MertBhey** [comment]
**wb.düzelt** yazdığınız zaman hata düzelmektedir. Gelecek güncelleme ile **wb.düzelt** yazılmadan  otomatik olarak düzeltme eklenebilir
