### ISSUE TITLE
(Fikir/Öneri) KoiosBot Yasaklama Komutları Önerisi

### ISSUE THREAD

**Issue by qreardedwastakennN** [fluxteam/IssueTracker#44]
- [x] Daha önceden açılan fikirleri/önerileri kontrol ettim ve aşağıda belirteceğim fikre/öneriye benzer bir fikir/öneri bulamadım. 

- [x] KoiosBot

**k!ban** - **k!kick** Komutları kullanımında bir problem yok. Hatta gayet gerektiğinden güzel çalışıyor ID ile ban falan. Gayet her şey güzel ancak bu komutlarda süre ile ban yapamıyoruz. Bir kez banlıyorsak o artık süresiz. Bir süre belirtebilirsek gayet iyi olabilir.

Bir alternatif belirtilmedi.

Ek belirtilmedi.

**Comment by Hagfog** [comment]
Şu anlık süreli ban sistemi üzerinde çalışılmayacaktır. Yine de not alındı. Eklenmesi durumunda bu issue üzerinde gerekli güncelleme yapılacaktır.
