### ISSUE TITLE
(Fikir/Öneri) KoiosBot Hata Kodları

### ISSUE THREAD

**Issue by qreardedwastakennN** [fluxteam/IssueTracker#45]
- [x] Daha önceden açılan fikirleri/önerileri kontrol ettim ve aşağıda belirteceğim fikre/öneriye benzer bir fikir/öneri bulamadım.
- [x] Bu fikri/öneriyi bir hata'nın çözümü adına yapmaktayım.

- [x] KoiosBot

Belirli komutlar kullanıldığında hata kodlarıyla karşılaşıyoruz ve her hata için Hagfog'a ya da destek  sunucusuna girip hata kodunu vermemiz biraz gereksiz. 
Bazı hataları bot kendisi tespit edip bunun için şurada hata yaptınız şöyle kullanın gibi bir mesaj gönderebilir ya da **k!hata-kodları** diye bir komut üzerinden hata kodları ve açıklamalarını görüntüleyebiliriz.

![Screenshot_20210406-080450~2.png](https://user-images.githubusercontent.com/78941156/113661985-d613d800-96af-11eb-97b0-518ac2867470.png)

Örnek olarak yukarıda gördüğünüz fotoğraftaki hata kodu. Açıkçası ben biliyorum nerede hata yaptığımı ve neden hata kodu mesajı attığını. Ancak bunu herkes bilemeyebilir.

**Comment by Hagfog** [comment]
Ekran görüntüsünde gösterilen hata kodu sadece şu anlık sadece avatar komutunda aktif olan bir hata kodudur. Ve düzeltilecektir. Bunun dışında yapılan hatalarda düzeltmek için gereken adımlar sağlanmaktadır. Örneğin **k!sustur** yazarsanız gereken adımlar gösterilecektir. Ya da komutu yazarken bir hata yaparsanız nerede hata yaptığınız gösterilmektedir. Farklı bir öneri/tavsiye var ise lütfen belirtin.

**Comment by qreardedwastakennN** [comment]
Zaman geçtikçe eklenen komutlar doğrultusunda yukarıda belirtilen öneri belki bir ihtimal tekrardan konuşulabilir. _Yani yine tekrar bir yönerge belirtilir komut üzerine ancak bazı eklenen komutlar yukarıdaki öneri tekrardan düşünülebilir bence._

**Comment by Hagfog** [comment]
Gerekli olması durumunda değerlendirilecektir.
