### ISSUE TITLE
Wordbot Art arda Special Word

### ISSUE THREAD

**Issue by SupporttX** [fluxteam/IssueTracker#5]
**Başlamadan önce;**
- [x] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok. (Köşeli parantezin içine 'X' yazınız)
- [X] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor. (Köşeli parantezin içine 'X' yazınız)

**Bu hata raporunu WordBot  için açtım;**

**Hatanın açıklaması;**
WordBot`un Special World`ü art arda atması.

**Yeniden üretme adımları;**
Bu davranışı yeniden üretmek için gereken adımlar:
1. Şu kanala gidin 'wb-lab'
2. Oyunu oynayın
3. Hatayı gözlemleyin (Bu hata sürekli oluşmamaktadır)

**Beklenen davranış;**
Special World Art arda 1 kere gönderilmeli.

**Yerine görülen davranış;**
Special World art arda atılması ve bi önceki Special World`ün geçersiz sayılması

**Ekran görüntüleri;**
![wordbot](https://user-images.githubusercontent.com/51127058/106362154-5c1f4580-6332-11eb-9101-deaef571a807.png)

**Sunucu ID'si;**
788392350043996190

**Ek bilgiler;**
Ek bilgi bulunmamakta.

**Comment by Zamion101** [comment]
2 kere gönderme durumu ping ve şans faktörünün beta sürecinde fazla olmasından kaynaklanıyor olabilir. Bu sorunu çözmek için eğer aktif bir `Özel Kelime` var ise aktif olan'ın süresi dolana kadar yeni bir özel kelime bildirisi gönderilmeyecek şekilde ayarlanmıştır.

**Comment by Teo00** [comment]
Sorunun devam edip etmediği doğrulanana kadar Issue kapatılmıştır. Hala devam ediyorsa yeni bir tane açıp, bu sorunu etiketleyebilirsiniz.
