### ISSUE TITLE
Wordbot Special World 

### ISSUE THREAD

**Issue by SupporttX** [fluxteam/IssueTracker#6]
**Başlamadan önce;**
- [x] Daha önceden önerilen özellikleri kontrol ettim. Benzer bir öneri yok. (Köşeli parantezin içine 'X' yazınız)
- [x] (HATA ALIYORSANIZ DOLDURUN) Botun gerekli izinlerinin olup olmadığını kontrol ettim. (Köşeli parantezin içine 'X' yazınız)

**Bu fikir/öneri Wordbot için;**

**Önerdiğiniz özellik bir hataya bağlı mı? Lütfen açıklayın;**
Hayır.

**Bu çözüme ürettiğiniz alternatifler;**
Wordbot Special Word verdiği kelimeyi yazan kişinin mesajına normal Wordbot Tepkisi değil farklı bir tepki koyabilir daha hoş olacağını düşünüyorum.
 
**Sunucu ID'si;**
Buraya ilgili botun bulunduğu sunucunun ID'sini yazınız. (Bu çok da gerekli değildir. Fakat bir soruna bağlı bu özelliği istiyorsanız lütfen doldurun.)

**Ek bilgiler;**
Yok.

**Comment by Zamion101** [comment]
Bu öneri daha önce de bahsedilip eklenmiştir. Şu andan itibaren tüm Özel Kelime bulunmasına sebep olan kelime'ye `🌟` emojisi konulmaktadır. Öneriniz için teşekkür ederim.
