### ISSUE TITLE
KoiosBot k!sıralama Öneri 

### ISSUE THREAD

**Issue by qreardedwashere** [fluxteam/IssueTracker#7]
- [x] Daha önceden önerilen özellikleri kontrol ettim. Benzer bir öneri yok.

**Bu fikir/öneri şu bot için;**
KoiosBot

**Önerdiğiniz özellik bir hataya bağlı mı? Lütfen açıklayın;**
KoiosBot Seviye sistemi aktifleştirildiğinde k!sıralama komutunu kullanınca sıralama menüsünde kullanıcı bulunmayınca No Data ismiyle gösteriyor.

**Kendi ürettiğiniz çözüm;**
Sıralamada eğer kimse yoksa ayrı bir mesaj, sıralamada örnek olarak 1 kişi varsa sadece 1 kişinin mesajını gönderebilir. Alt alta No Data yazmayabilir.

**Bu çözüme ürettiğiniz alternatifler;**
Eğer bir kişinin seviyesi yoksa "Seviyesi Yok" gibi belirtilebilir.

**Sunucu ID'si;**
798999365271552050

**Ek bilgiler;**
[Screenshot_20210130-205648~2.png](https://user-images.githubusercontent.com/65084643/106364434-05206d00-6340-11eb-81ce-816a9cbf6051.png)

**Comment by qreardedwashere** [comment]
**Bir önerim daha:**
Sıralama menüsü biraz sade, bence biraz kötü duruyor.
Kişinin isminin başına profil fotoğrafı gelebilir.
**Sıralama** başlığına komutun kullanıldığı sunucu getirilebilir.
Ve **footer kısmı** ( ismi aklıma gelmedi böyle idare edin. ) oraya "Bu sunucunun seviye sistemini KoiosBot karşılıyor." gibi gibi şeyler eklenebilir. Menü(ler) zenginleştirilebilir.

**Comment by Hagfog** [comment]
Sıralama tablosunda bulunan "No Data" yazıları sıradaki güncelleme ile düzeltilecektir, not aldım. Sıralama tablosunun genel tasarım itibari ile değişmesi ise planlar arasında yer alıyor. Şu an kullandığımız embed aracılığı ile kişinin isminin başına profil fotoğrafı getirilmesi mümkün değil maalesef.
