### ISSUE TITLE
(Fikir/Öneri) WordBot Yardım Menüsü Önerisi

### ISSUE THREAD

**Issue by qreardedwashere** [fluxteam/IssueTracker#8]
[x] Daha önceden önerilen özellikleri kontrol ettim. Benzer bir öneri yok.

**Bu fikir/öneri şu bot için;**
_WordBot Beta_

**Belirttiğim fikir:**
Yardım menüsündeki işlemler WordBot'un özel mesaj kısmından halledilebilir. Bu biraz gereksiz veya yapılsa bile uğraştırıcı olabilir, ancak yapıldığı zaman da bence takdir toplayabilir. ( açıkçası benim açımdan. ) Temel olarak sayfalı sisteme geçilip her şey oradan halledilebilir. Webpanel gibi.

**Alternatif olarak:**
Bunun yerine özel mesaj kısmından değilde sayfalı sisteme geçilmesi açıkçası bence gayet güzel olabilir, veya komutlar kategorize biçime taşınabilir.

**WordBot** _798999365271552050_ **ID'li sunucuda kullanılıyor.**

**Eklenmek istenilen ek bilgi bulunmamaktadır.**

**Comment by Zamion101** [comment]
Konu hakkında daha anlaşılabilir ve detaylı bilgiye ihtiyaç vardır. Olası kategoriler nelerdir? Sayfalı sistemden kastınız nedir? Web Panel üzerindeki işlemler hakkında küçük bir açıklama. İşlemlerden (oyun başlatma/bitirme? limit değiştirme? vb.?) kastınız nelerdir? Bu gerekli bilgiler doğrultusunda konu hakkında ileri ki zamanlarda daha detaylı olarak konuşulacaktır.

**Comment by qreardedwashere** [comment]
Biraz kötü yazılmış farkettim kusura bakmayın.

**Kastedilmek istenilen durum:**
Sayfa sistemi, embedler arasında tepkiler üzerinden geçişler kastedildi.
Web panel bir örneklemeydi ciddiye almayın.
Kategori ise, wb.yardım ana-sistemler gibi bu bir örnekti.
_Komutları ayrıştırmak. Yerine göre belirlemek._

**Comment by Zamion101** [comment]
Öncelikle geç cevap için özür dilerim. Bahsetmiş olduğunuz `Kategoriler` yardım menüsüne eklenebilir. Fakat Özel mesajlardan yönetim kısmı biraz sıkıntı. Sıkıntı olma sebebi ise `Discord'un Shard Sistemi`. Discord Shard sistemi WordBot'a atılan **tüm özel mesajları** 0. Shard'a göndermektedir. Eğer bu özellik eklenir ise bazı kişiler bu durumdan istifade edip 0. Shard üzerinde ağır bir yük oluşmasına sebep olabilir. Bu durumda 0.Shard üzerindeki tüm WordBot oyunları `gecikmeye yada kesintiye` uğrayabilir. Bu nedenden dolayı ne yazık ki Özel Mesajlar üzerinden yardım kısmını eklemeyi **şuan için** hem doğru bulmuyorum hemde düşünmüyorum.
