### ISSUE TITLE
KoiosBot Help Komutundaki Support Server Daveti Geçersiz

### ISSUE THREAD

**Issue by VerdantString** [fluxteam/IssueTracker#9]
**Başlamadan önce;**
- [X] Daha önceden açılmış hata raporlarını kontrol ettim. Benzer bir hata raporu yok. (Köşeli parantezin içine 'X' yazınız)
- [X] Botun gerekli izinlerinin olup olmadığını kontrol ettim. Her şey doğru gözüküyor. (Köşeli parantezin içine 'X' yazınız)

**Bu hata raporunu şu bot için açtım;**
KoiosBot

**Hatanın açıklaması;**
Help komutundaki support server daveti geçersiz.

**Yeniden üretme adımları;**
Bu davranışı yeniden üretmek için gereken adımlar:
1. KoiosBotun bulunduğu sunucuya giriş yapın
2. Sunucuda her hangi bir odaya girin
3. Şu komutu kullanın 'k!help'
4. Botun özelden attığı mesaja girin
5. Aşağıdan Support Server altındaki 'Join' butonuna tıklayın
6. Hatayı gözlemleyin

**Beklenen davranış;**
Join butonuna basılınca kullanıcının botun destek sunucusuna giriş sağlaya bilmesi.

**Yerine görülen davranış;**
Join butonuna basılınca botun hiç bir şekilde tepki vermemesi.

**Ekran görüntüleri;**
![image](https://user-images.githubusercontent.com/78115411/106363087-6e4fb280-6337-11eb-8877-09814214eaa3.png)

**Sunucu ID'si;**
805104802668216340

**Ek bilgiler;**
Davet linkinin geçersiz olması

**Comment by Teo00** [comment]
Sorunun var olduğu onaylandı.

**Comment by Hagfog** [comment]
Sorun düzeltildi.
